### ISSUE TITLE
Add stac-utils as a PyPI maintainer

### ISSUE THREAD

**Issue by gadomski** [stactools-packages/sentinel3#11]
The CI release process uses the [stac-utils user](https://pypi.org/user/stac-utils/) to publish. The [sentinel3 stactools package on PyPI](https://pypi.org/project/stactools-sentinel3/) currently has one maintainer, https://pypi.org/user/chorng/:

![Screenshot 2023-03-16 at 07-42-49 stactools-sentinel3](https://user-images.githubusercontent.com/58314/225636025-78af81aa-2dcd-4673-bc7a-34a5a182e9f5.png)

@chorng, can you add https://pypi.org/user/stac-utils/ as a maintainer so we can publish releases? Thanks!

**Comment by gadomski** [comment]
Thank you so much, accepted here and for **sentinel5p**. Could you please make **stac-utils** an owner as well, since we'll be publishing from this repo's CI?

**Comment by chorng** [comment]
I think the maintainer role gives permission to upload releases (see the attached figure). Is there a specific reason why an owner role is needed in this case?

> Maintainer has permissions to upload releases for the project. Can upload releases. Cannot invite collaborators. Cannot delete files, releases, or the project.

**Comment by gadomski** [comment]
Since the package is in the **stactools-packages** organization, it makes sense (to me at least) for **stac-utils** to be an owner (you can have multiple owners).

**Comment by chorng** [comment]
Understood. I assigned the owner role for both projects.

**Comment by gadomski** [comment]
Thanks! Really appreciate it!
